"""empty message

Revision ID: 0896b768235d
Revises: 3666d2203718
Create Date: 2024-06-24 18:48:04.503068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0896b768235d'
down_revision = '3666d2203718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], referent_schema='gama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_ibfk_1', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
