"""empty message

Revision ID: 64bd52f4229b
Revises: 748d0742c777
Create Date: 2024-07-04 09:17:44.692755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision = '64bd52f4229b'
down_revision = '748d0742c777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if 'user' table exists in the 'gama' schema
    if 'user' not in inspector.get_table_names(schema='gama'):
        op.create_table('user',
                        sa.Column('user_id', sa.Integer(), nullable=False),
                        sa.Column('email', sa.String(length=120), nullable=False),
                        sa.Column('password', sa.String(length=512), nullable=False),
                        sa.Column('user_name', sa.String(length=120), nullable=False),
                        sa.PrimaryKeyConstraint('user_id'),
                        sa.UniqueConstraint('email'),
                        sa.UniqueConstraint('user_name'),
                        schema='gama'
                        )

    # Check if 'player' table exists in the 'gama' schema
    if 'player' not in inspector.get_table_names(schema='gama'):
        op.create_table('player',
                        sa.Column('player_id', sa.Integer(), nullable=False),
                        sa.Column('name', sa.String(length=120), nullable=False),
                        sa.Column('type', sa.String(length=120), nullable=False),
                        sa.Column('score', sa.Integer(), nullable=False),
                        sa.Column('level', sa.Integer(), nullable=False),
                        sa.Column('user_id', sa.Integer(), nullable=False),
                        sa.ForeignKeyConstraint(['user_id'], ['gama.user.user_id'], ),
                        sa.PrimaryKeyConstraint('player_id'),
                        schema='gama'
                        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player', schema='gama')
    op.drop_table('user', schema='gama')
    # ### end Alembic commands ###
