"""empty message

Revision ID: 748d0742c777
Revises: da246cb1afc6
Create Date: 2024-06-28 18:03:48.119068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748d0742c777'
down_revision = 'da246cb1afc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], referent_schema='gama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_ibfk_1', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
