"""empty message

Revision ID: da246cb1afc6
Revises: e86bce04f0a3
Create Date: 2024-06-27 13:12:15.249042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da246cb1afc6'
down_revision = 'e86bce04f0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('player_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], referent_schema='gama')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_ibfk_1', 'user', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
