"""empty message

Revision ID: fa781c7a5b54
Revises: cad764bec8ee
Create Date: 2024-06-24 17:14:19.649435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa781c7a5b54'
down_revision = 'cad764bec8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS gama.player')
    op.execute('DROP TABLE IF EXISTS gama.user')

    op.create_table(
        'user',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('user_id'),
        schema='gama'
    )

    op.create_table(
        'player',
        sa.Column('player_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['gama.user.user_id']),
        sa.PrimaryKeyConstraint('player_id'),
        schema='gama'
    )
    # ### end Alembic commands ### batch_op.drop_column('id')



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('player_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
